apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ include "mgnl.author.name" . }}
  labels:
    {{- include "mgnl.labels" . | nindent 4 }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: magnolia-author