{{- if eq (include "mgnl.ingress.controller" .) "traefik" -}}
{{- if .Values.magnoliaAuthor.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "mgnl.name" . }}-buffering
  labels:
    {{- include "mgnl.labels" . | nindent 4 }}
spec:
  buffering:
    maxRequestBodyBytes: 52428800
    memRequestBodyBytes: 52428800
{{- end }}
{{- if or .Values.magnoliaAuthor.assetIngress.enabled .Values.magnoliaPublic.assetIngress.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "mgnl.name" . }}-assets-add-dam-prefix
  labels:
    {{- include "mgnl.labels" . | nindent 4 }}
spec:
  addPrefix:
    prefix: /dam
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "mgnl.name" . }}-assets-robots
  labels:
    {{- include "mgnl.labels" . | nindent 4 }}
spec:
  headers:
    customResponseHeaders:
      X-Robots-Tag: noindex
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "mgnl.name" . }}-assets
  labels:
    {{- include "mgnl.labels" . | nindent 4 }}
spec:
  chain:
    middlewares:
      - name: {{ include "mgnl.name" . }}-assets-add-dam-prefix
      - name: {{ include "mgnl.name" . }}-assets-robots
{{- end }}
{{- end }}
