{{- if .Values.magnolia.externalSecret.enabled }}
{{- $name := printf "%s-custom-env-secrets" (include "mgnl.name" .) }}
{{- $es := .Values.magnolia.externalSecret }}
{{ include "mgnl.externalSecret.head" (dict "name" $name "es" $es "root" .) }}
  data:
    {{- range $es.data }}
    - secretKey: {{ required "magnolia.externalSecret.data[].secretKey is required" .secretKey }}
      remoteRef:
        key: {{ required "magnolia.externalSecret.remoteKey is required" $es.remoteKey }}/{{ .property | default .secretKey }}
    {{- end }}
{{- end }}
