apiVersion: v1
kind: Service
metadata:
  name: {{ include "mgnl.public.name" . }}
  labels:
    {{- include "mgnl.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: magnolia-public
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- $ := . -}}
{{- $replicaCount := .Values.magnoliaPublic.replicaCount | int -}}
{{ range $i := until $replicaCount }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mgnl.public.name" $ }}-{{$i}}
  labels:
{{ include "mgnl.labels" $ | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: magnolia-public
    app.kubernetes.io/instance: {{ $.Release.Name }}
    statefulset.kubernetes.io/pod-name: {{ include "mgnl.public.name" $ }}-{{$i}}
{{ end }}