{{- if .Values.magnoliaPublic.ingress.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mgnl.public.name" . }}-tls
  labels:
{{ include "mgnl.labels" . | indent 4 }}
data:
  ca.crt: {{ .Values.magnoliaPublic.ingress.secret.ca | quote }}
  tls.crt: {{ .Values.magnoliaPublic.ingress.secret.cert | quote }}
  tls.key: {{ .Values.magnoliaPublic.ingress.secret.key | quote }}
type: "kubernetes.io/tls"
{{- end -}}