{{- if .Values.magnoliaAuthor.ingress.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mgnl.author.name" . }}-tls
  labels:
{{ include "mgnl.labels" . | indent 4 }}
data:
  ca.crt: {{ .Values.magnoliaAuthor.ingress.secret.ca | b64enc }}
  tls.crt: {{ .Values.magnoliaAuthor.ingress.secret.cert | b64enc }}
  tls.key: {{ .Values.magnoliaAuthor.ingress.secret.key | b64enc }}
type: "kubernetes.io/tls"
{{- end -}}