apiVersion: v1
kind: Service
metadata:
  name: {{ include "mgnl.author.name" . }}
  labels:
    {{- include "mgnl.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: magnolia-author
    app.kubernetes.io/instance: {{ .Release.Name }}
