apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mgnl.name" . }}-light-module-updater
  labels:
{{ include "mgnl.labels" . | indent 4 }}
data:
  tag: {{ .Values.magnoliaLightModuleUpdater.privateKey }}