{{- if .Values.magnoliaActivation.externalSecret.enabled }}
{{- $name := printf "%s-activation-keypair" (include "mgnl.name" .) }}
{{- $es := .Values.magnoliaActivation.externalSecret }}
{{ include "mgnl.externalSecret.head" (dict "name" $name "es" $es "root" .) }}
  data:
    - secretKey: magnolia-activation-keypair.properties
      remoteRef:
        key: {{ required "magnoliaActivation.externalSecret.remoteKey is required" $es.remoteKey }}
        property: {{ $es.properties.properties | default "magnolia-activation-keypair.properties" }}
{{- end }}
