{{- if .Values.magnoliaAuthor.datasource.externalSecret.enabled }}
{{- $name := printf "%s-datasource-password" (include "mgnl.author.name" .) }}
{{- $es := .Values.magnoliaAuthor.datasource.externalSecret }}
{{ include "mgnl.externalSecret.head" (dict "name" $name "es" $es "root" .) }}
  data:
    - secretKey: MGNL_AUTHOR_DB_PASSWORD
      remoteRef:
        key: {{ required "magnoliaAuthor.datasource.externalSecret.remoteKey is required" $es.remoteKey }}
        property: {{ $es.properties.password | default "MGNL_AUTHOR_DB_PASSWORD" }}
{{- end }}
