{{- if and .Values.license.enabled .Values.license.externalSecret.enabled }}
{{- $name := printf "%s-license" (include "mgnl.name" .) }}
{{- $es := .Values.license.externalSecret }}
{{ include "mgnl.externalSecret.head" (dict "name" $name "es" $es "root" .) }}
  data:
    - secretKey: license.key
      remoteRef:
        key: {{ required "license.externalSecret.remoteKey is required" $es.remoteKey }}/{{ $es.properties.licenseKey | default "license.key" }}
    - secretKey: email
      remoteRef:
        key: {{ required "license.externalSecret.remoteKey is required" $es.remoteKey }}/{{ $es.properties.email | default "email" }}
{{- end }}
