{{- if .Values.magnoliaLightModuleUpdater.externalSecret.enabled }}
{{- $name := printf "%s-light-module-updater" (include "mgnl.name" .) }}
{{- $es := .Values.magnoliaLightModuleUpdater.externalSecret }}
{{ include "mgnl.externalSecret.head" (dict "name" $name "es" $es "root" .) }}
  data:
    - secretKey: private-key
      remoteRef:
        key: {{ required "magnoliaLightModuleUpdater.externalSecret.remoteKey is required" $es.remoteKey }}
        property: {{ $es.properties.privateKey | default "private-key" }}
{{- end }}
