apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mgnl.name" . }}-light-module-updater
  labels:
{{ include "mgnl.labels" . | indent 4 }}
data:
  tag: "{{- if typeIs "string" .Values.magnoliaLightModuleUpdater.tag }}{{ .Values.magnoliaLightModuleUpdater.tag }}{{ end }}"