{{- if .Values.mysql.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mgnl.mysql.name" . }}-config
  labels:
    {{- include "mgnl.labels" . | nindent 4 }}
data:
  init.sql: |
    {{- tpl (.Files.Get "magnolia.cnf") . | nindent 4 }}
{{- end -}}