{{- if and .Values.mysql.enabled .Values.mysql.externalSecret.enabled }}
{{- $name := printf "%s-passwords" (include "mgnl.mysql.name" .) }}
{{- $es := .Values.mysql.externalSecret }}
{{ include "mgnl.externalSecret.head" (dict "name" $name "es" $es "root" .) }}
  data:
    - secretKey: root
      remoteRef:
        key: {{ required "mysql.externalSecret.remoteKey is required" $es.remoteKey }}
        property: {{ $es.properties.root | default "root" }}
{{- end }}
