version: "3.4"
services:
  sut:
    build:
      dockerfile: ../Dockerfile
      context: build
    environment:
      LOG_LEVEL: DEBUG
      MAGNOLIA_CONFIG: foo
      DATASOURCES: |
        {
          "datasources": [
            {
              "name": "MagnoliaAuthor",
              "database": "author",
              "host": "db",
              "password": "<&%!^>",
              "username": "author"
            }
          ]
        }
  db:
    image: mysql:9.7.1@sha256:8fdf311514c91fa5014e93e98e19d7f5d9eb162a462c13100c956dacc278ee21
    environment:
      MYSQL_DATABASE: author
      MYSQL_USER: author
      MYSQL_PASSWORD: <&%!^>
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
