FROM ubuntu:18.04
COPY --from=gcr.io/kaniko-project/executor /kaniko /kaniko
ENV HOME /root
ENV USER /root
ENV PATH $PATH:/usr/local/bin:/kaniko
ENV DOCKER_CONFIG /kaniko/.docker/
ENV DOCKER_CREDENTIAL_GCR_CONFIG /kaniko/.config/gcloud/docker_credential_gcr_config.json
WORKDIR /workspace
RUN ["docker-credential-gcr", "config", "--token-source=env"]
CMD [ "/kaniko/executor" ]