
version: "3.4"
services:
  sut:
    build:
      dockerfile: ../Dockerfile
      context: build
    environment:
      LOG_LEVEL: DEBUG
      DATASOURCES: |
        {
          "datasources": [
            {
              "name": "MagnoliaAuthor",
              "database": "author",
              "host": "db",
              "password": "<&%!^>",
              "username": "author",
              "useSsl": true,
              "trustStore": "/tmp/truststore.jks",
              "trustStorePassword": "changedit",
              "enabledTLSProtocols": "TLSv1.2"
            }
          ]
        }
    volumes:
      - ./truststore.jks:/tmp/truststore.jks:ro
  db:
    image: mysql:8.1.0
    environment:
      MYSQL_DATABASE: author
      MYSQL_USER: author
      MYSQL_PASSWORD: <&%!^>
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    command:
      - --bind-address=0.0.0.0
      - --require_secure_transport=ON
      - --ssl
      - --default_authentication_plugin=mysql_native_password
      - --tls_version=TLSv1.2