name: Build LMU

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set TAG
        run: echo "TAG=${GITHUB_REF_NAME#mgnl-}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push LMU image
        uses: docker/build-push-action@v6
        with:
          context: ./images/light-module-updater
          file: ./images/light-module-updater/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            neoskop/mgnl-light-module-updater:${{ env.TAG }}

  notify-failure:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - uses: slackapi/slack-github-action@v1
        with:
          payload: '{"text": "*[mgnl-on-k8s]:* Bauen des LMU-Images ist fehlgeschlagen"}'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
