name: Build webapp images

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 4 * * *'

env:
  NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  MIN_VERSION: 6.3.15

jobs:
  get-versions:
    runs-on: ubuntu-20.04
    outputs:
      versions: ${{ steps.set-versions.outputs.versions }}
    steps:
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y xmlstarlet curl

      - id: set-versions
        run: |
          versions=$(curl -s https://nexus.magnolia-cms.com/repository/public/info/magnolia/magnolia-empty-webapp/maven-metadata.xml \
            | xmlstarlet sel -t -v '//metadata/versioning/versions/version/text()' - \
            | sort -V -r)
          result=""
          for v in $versions; do
            if [ "$(printf '%s\n' "$MIN_VERSION" "$v" | sort -V | head -n1)" = "$MIN_VERSION" ] \
              && ! echo "$v" | grep -Pqi 'snapshot|beta|alpha|rc'; then
              result="$result $v"
            fi
          done
          echo "versions=$result" >> $GITHUB_OUTPUT

  build-wars:
    runs-on: ubuntu-latest
    needs: get-versions
    strategy:
      matrix:
        version: ${{ fromJSON('["' + join(needs.get-versions.outputs.versions, '","') + '"]') }}
        flavor: [dx-damfs, ce-damfs, dx, ce]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Configure Maven settings
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <localRepository>/home/runner/.m2/repository</localRepository>
            <servers>
              <server>
                <id>magnolia.enterprise</id>
                <username>${NEXUS_USERNAME}</username>
                <password>${NEXUS_PASSWORD}</password>
              </server>
              <server>
                <id>magnolia.enterprise.releases</id>
                <username>${NEXUS_USERNAME}</username>
                <password>${NEXUS_PASSWORD}</password>
              </server>
            </servers>
          </settings>
          EOF

      - name: Build WAR for ${{ matrix.version }} ${{ matrix.flavor }}
        run: |
          edition=$(echo "${{ matrix.flavor }}" | cut -c 1-2)
          mkdir build && cd build
          cp $GITHUB_WORKSPACE/images/webapp/magnolia-build/$edition/pom.parent.xml pom.xml
          mkdir -p ./webapp/src/main/webapp
          cp $GITHUB_WORKSPACE/images/webapp/magnolia-build/$edition/pom.webapp.xml webapp/pom.xml
          cp -r $GITHUB_WORKSPACE/images/webapp/magnolia-build/WEB-INF ./webapp/src/main/webapp/WEB-INF

          if [[ "$edition" == "ce" ]]; then
            xmlstarlet ed -L -N p="http://maven.apache.org/POM/4.0.0" \
              -d "//p:dependency[p:artifactId='magnolia-site-app']" webapp/pom.xml
          else
            sed -i s/MagnoliaWidgetSet/MagnoliaProWidgetSet/ ./webapp/src/main/webapp/WEB-INF/config/default/magnolia.properties
          fi

          if [[ "${{ matrix.flavor }}" == *-damfs ]]; then
            find ./webapp/src/main/webapp/WEB-INF -name magnolia.properties \
              -exec sed -i 's|repo-conf/author.xml|repo-conf/author-damfs.xml|g; s|repo-conf/public.xml|repo-conf/public-damfs.xml|g' {} \;
          fi

          mvn -DmagnoliaBundleVersion=${{ matrix.version }} -T 8 package
          mkdir -p $GITHUB_WORKSPACE/artifacts/${{ matrix.flavor }}
          mv ./webapp/target/webapp.war $GITHUB_WORKSPACE/artifacts/${{ matrix.flavor }}/webapp-${{ matrix.version }}.war

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: war-${{ matrix.flavor }}-${{ matrix.version }}
          path: artifacts/${{ matrix.flavor }}/webapp-${{ matrix.version }}.war

  build-images:
    runs-on: ubuntu-latest
    needs: build-wars
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Download WAR artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Build & push images
        run: |
          for flavor in dx-damfs ce-damfs dx ce; do
            for version in $(ls artifacts/$flavor | sed 's/webapp-//; s/.war//'); do
              tag=docker.io/neoskop/mgnl-webapp-$flavor:$version
              docker buildx build \
                --platform linux/amd64,linux/arm64 \
                --build-arg VERSION=$version \
                --build-arg NEXUS_USERNAME=$NEXUS_USERNAME \
                --build-arg NEXUS_PASSWORD=$NEXUS_PASSWORD \
                -t $tag \
                -f ./images/webapp/magnolia-build/$flavor/Dockerfile \
                ./images/webapp/magnolia-build \
                --push
            done
          done

  notify-failure:
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1
        with:
          payload: |
            {
              "text": "*[mgnl-on-k8s]:* Bauen der Webapp-Images ist fehlgeschlagen"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
